# Code generated by `$ mix hipchat.generate`
defmodule Hipchat.V2.Api.Emoticons do
  @moduledoc """
  HipChat V2 Emoticons API module.
  """

  alias Hipchat.V2.Client

  @doc """
  Gets all emoticons for the current group

  Authentication required, with scope view_group.

  Accessible by group clients, room clients, users.

  https://www.hipchat.com/docs/apiv2/method/get_all_emoticons
  """
  @spec get_all_emoticons(Client.t, list) :: Client.res_t
  def get_all_emoticons(client, query_params) do
    Client.send_request(client, :get, "/emoticon", query_params, nil)
  end

  @doc """
  Get emoticon details.

  Authentication required, with scope view_group.

  Accessible by group clients, room clients, users.

  https://www.hipchat.com/docs/apiv2/method/get_emoticon
  """
  @spec get_emoticon(Client.t, String.t) :: Client.res_t
  def get_emoticon(client, emoticon_id_or_key) do
    Client.send_request(client, :get, "/emoticon/#{emoticon_id_or_key}", [], nil)
  end
end
