# Code generated by `$ mix hipchat.generate`
defmodule Hipchat.V2.Api.Extensions do
  @moduledoc """
  HipChat V2 Extensions API module.
  """

  alias Hipchat.V2.Client

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/create_global_action](https://www.hipchat.com/docs/apiv2/method/create_global_action)
  """
  @spec create_global_action(Client.t, String.t, map) :: Client.res_t
  def create_global_action(client, key, body) do
    Client.send_request(client, :put, "/extension/action/#{key}", [], body)
  end

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/delete_global_action](https://www.hipchat.com/docs/apiv2/method/delete_global_action)
  """
  @spec delete_global_action(Client.t, String.t) :: Client.res_t
  def delete_global_action(client, key) do
    Client.send_request(client, :delete, "/extension/action/#{key}", [], %{})
  end

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/get_global_action](https://www.hipchat.com/docs/apiv2/method/get_global_action)
  """
  @spec get_global_action(Client.t, String.t) :: Client.res_t
  def get_global_action(client, key) do
    Client.send_request(client, :get, "/extension/action/#{key}", [], %{})
  end
end
