# Code generated by `$ mix hipchat.generate`
defmodule Hipchat.V2.Api.Groups do
  @moduledoc """
  HipChat V2 Groups API module.
  """

  alias Hipchat.V2.Client

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/delete_group_avatar](https://www.hipchat.com/docs/apiv2/method/delete_group_avatar)
  """
  @spec delete_group_avatar(Client.t, String.t) :: Client.res_t
  def delete_group_avatar(client, group_id) do
    Client.send_request(client, :delete, "/group/#{group_id}/avatar", [], %{})
  end

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/view_group](https://www.hipchat.com/docs/apiv2/method/view_group)
  """
  @spec get_group(Client.t, String.t) :: Client.res_t
  def get_group(client, group_id) do
    Client.send_request(client, :get, "/group/#{group_id}", [], %{})
  end

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/get_group_avatar](https://www.hipchat.com/docs/apiv2/method/get_group_avatar)
  """
  @spec get_group_avatar(Client.t, String.t) :: Client.res_t
  def get_group_avatar(client, group_id) do
    Client.send_request(client, :get, "/group/#{group_id}/avatar", [], %{})
  end

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/group_statistics](https://www.hipchat.com/docs/apiv2/method/group_statistics)
  """
  @spec get_group_statistics(Client.t, String.t) :: Client.res_t
  def get_group_statistics(client, group_id) do
    Client.send_request(client, :get, "/group/#{group_id}/statistics", [], %{})
  end

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/update_group_avatar](https://www.hipchat.com/docs/apiv2/method/update_group_avatar)
  """
  @spec update_group_avatar(Client.t, String.t, map) :: Client.res_t
  def update_group_avatar(client, group_id, body) do
    Client.send_request(client, :put, "/group/#{group_id}/avatar", [], body)
  end
end
