# Code generated by `$ mix hipchat.generate`
defmodule Hipchat.V2.Api.Rooms do
  @moduledoc """
  HipChat V2 Rooms API module.
  """

  alias Hipchat.V2.Client

  @doc """
  [https://www.hipchat.com/docs/apiv2/method/send_room_notification](https://www.hipchat.com/docs/apiv2/method/send_room_notification)
  """
  @spec send_room_notification(Client.t, String.t, map) :: Client.res_t
  def send_room_notification(client, room_id_or_name, body) do
    Client.send_request(client, :post, "/room/#{room_id_or_name}/notification", [], body)
  end
end
