defmodule Mix.Tasks.Hipchat.Generate do
  @shortdoc "Generate API modules from spec YAML"
  @moduledoc """
  #{@shortdoc}.

  This task does not need to be run on user side at all.
  Latest API should be generated by the library maintainers and published in Hex.
  """

  use Mix.Task

  def run(_args) do
    Application.ensure_started(:yamerl)
    Hipchat.Generator.generate()
  end
end
